# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Release App
on:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: write

jobs:

  build-linux:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install build
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Package
      run: |
        python -m build
        
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        prerelease: ${{ contains(github.ref, '-') }}



  build-win:

    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip build virtualenv
        python -m pip install -r requirements.txt
    - name: Package
      run: |
        python -m build
        scripts\build_installer.bat
        
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*.whl
          scripts/Output/*.exe
        prerelease: ${{ contains(github.ref, '-') }}

        

  build-macos:

    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python3 -V
        python3 -m pip install --upgrade pip build virtualenv PyInstaller
        python3 -m virtualenv venv
        source venv/bin/activate
        python -m pip install -r requirements.txt
        git describe --all
    - name: Test with pytest
      run: |
        source venv/bin/activate
        python3 -m pip install pytest
        make dev
        pytest tests
    - name: Package
      run: |
        python3 -m build
        source venv/bin/activate
        make pyinstaller
    - name: Zip
      run: |
        (cd dist_pyi && zip -r PRE_Workbench_macOS_$(git describe --tags).zip PRE\ Workbench.app)
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist_pyi/*.zip
          dist/*.whl
        prerelease: ${{ contains(github.ref, '-') }}

        
